spring:
  datasource:
    url: jdbc:mysql://localhost/firstproject
    username: root 
    password: root@123 
    driver-class-name:  com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 5MB
          
    
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
            